# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Revision'), (3, 'Published')], default=1),
        ),
    ]
